export const Selectors = {
  Home: {
    loginDialog: "[data-cy=login-dialog]",
    usernameInput: "[data-cy=login-username]",
    passwordInput: "[data-cy=login-password]",
    passwordConfirmationInput: "[data-cy=password-confirmation]",
    signInButton: "[data-cy=sign-in-button]",
    registerButton: "[data-cy=register-button]",
    enterRegistrationModeButton: "[data-cy=enter-registration-mode]",
  },
  DocumentList: {
    documentListDiv: "[data-cy=document-list]",
    beginAddDocumentButton: "[data-cy=begin-add-document]",
    documentCreationDialog: "[data-cy=document-creation-dialog]",
    documentNameInput: "[data-cy=document-name-input]",
    documentSaveButton: "[data-cy=save-document-button]",
    allDocumentCards: "[data-cy^=document-card-]",
    anyDocumentCard: `[data-cy*="document-card"]`,
  },
  DocumentViewer: {
    documentTitle: "[data-cy=document-title]",
    documentTitleInputText: "[data-cy=document-title-editor]",
    compiledMarkdownOnlyViewButton:
      "[data-cy=compiled-markdown-only-view-button]",
    splitPaneViewButton: "[data-cy=split-pane-view-button]",
    editorOnlyViewButton: "[data-cy=editor-only-view-button]",
    markdownEditorInstance: "[data-cy=markdown-editor-instance]",
    markdownDisplayInstance: "[data-cy=markdown-display-instance]",
    addPageButton: "[data-cy=add-page-button]",
    closeGalleryButton: "[data-cy=close-gallery-button]",
    lightboxWrapper: "[data-cy=lightbox-wrapper]",
    deletePageButton: "[data-cy=delete-page-button]",
    cypressTestGalleryAnchor: `a[data-name='Cypress Test Gallery']`,
    documentImageGallery: "[data-cy=document-image-gallery]",
    missingGalleryError: "[data-cy=missing-gallery-error]",
    lightboxTrigger: "[data-cy=lightbox-trigger]",
    primeGalleriaImage: "[data-cy=prime-galleria-image]",
  },
  GalleryManager: {
    manageGalleriesButton: "[data-cy=manage-galleries-button-desktop]",
    galleryManagerModal: "[data-cy=gallery-manager-modal]",
    anyDeleteGalleryButton: `[data-cy*="delete-gallery-button"`,
    galleryNameEditor: "[data-cy=gallery-name-editor]",
    anyDeleteImageButton: `[data-cy*="image-delete-button"]`,
    anyGalleryInstanceInList: `[data-cy*="gallery-instance"]`,
    addImageButton: "[data-cy=add-image-button]",
    imageFileInput: "[data-cy=image-file-input]",
    addGalleryButton: "[data-cy=add-gallery-button]",
    saveGalleryButton: "[data-cy=save-gallery-button]",
    anyGalleryImageInEditor: `[data-cy*="gallery-image-in-editor"`,
  },
  ConfirmationModal: {
    deleteButton: "[data-cy=confirmation-modal-delete-button]",
  },
};
